### ISSUE TITLE
Exported mp4 encoded in vp8 (video) and opus (audio)

### ISSUE THREAD

**Issue by Hammadr097** [argodeep/Yotube-Tutorial-Maker#2]
This is simply an exported webm renamed as the mp4 extension, the encoding is not natively supported by Quicktime hence practically of limited use.

**Comment by argodeep** [comment]
Hi @Hammadr097 I have fixed the issue. Also pushed the changes. I was trying to fix the codec part to support mp4. For now, default format is webmm. Planning to use ffmpeg to convert into mp4.
